version: "3.8"

services:
  backend:
    build: .
    container_name: spaceship-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3.9-management"
    container_name: spaceship-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
