CREATE TABLE IF NOT EXISTS SPACESHIP (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SPACESHIP_NAME VARCHAR(255) NOT NULL,
    TV_PROGRAM VARCHAR(255) NOT NULL,
    CAPACITY INT,
    LAST_UPDATE TIMESTAMP,
    CONSTRAINT IDX_SPCACECHIP_UNQ UNIQUE (SPACESHIP_NAME, TV_PROGRAM)
);